// Shared types used across all domain categories

export type {
  Brand,
  Unbrand,
  UserId,
  WorldId,
  TagId,
  EntityDefinitionId,
  PropertyDefinitionId,
  PropertyId,
  EntityId,
  RelationshipDefinitionId,
  RelationshipId,
  BodySegmentId as EmbeddingChunkId,
  QueryId,
} from './ids';

export {
  userId,
  worldId,
  tagId,
  entityDefinitionId,
  propertyDefinitionId,
  propertyId,
  entityId,
  relationshipDefinitionId,
  relationshipId,
  embeddingChunkId,
  queryId,
  createUserId,
  createWorldId,
  createTagId,
  createEntityDefinitionId,
  createPropertyDefinitionId,
  createPropertyId,
  createEntityId,
  createRelationshipDefinitionId,
  createRelationshipId,
  createEmbeddingChunkId,
  createQueryId,
  isValidUuid,
} from './ids';
